
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: employee-management-service
spec:
  selector:
    app: employee-management
  ports:
    - protocol: "TCP"
      port: 9292 # The port that the service is running on in the cluster
      targetPort: 9292 # The port exposed by the service
  type: LoadBalancer # type of the service.
