apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management-deployment
spec:
  selector:
    matchLabels:
      app: employee-management
  replicas: 3
  template:
    metadata:
      labels:
        app: employee-management
    spec:
      containers:
        - name: employee-management-container
          image: vedikavdeshmukh/employeemanagement:latest
          ports:
            - containerPort: 9292
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysql

            - name: DB_NAME  # Setting Database name from configMap
              value: Employee_Management_System

            - name: DB_USERNAME  # Setting Database username from Secret
              value: root

            - name: DB_PASSWORD # Setting Database password from Secret
              value: root
